apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: can-parser-job-prod
  namespace: flink-prod
spec:
  serviceAccount: flink-prod
  mode: native
  image: 534375227638.dkr.ecr.ap-south-1.amazonaws.com/se-prod-flink-can-parser:v1.0.5
  flinkVersion: v1_20
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "10"
    # execution.checkpointing.interval: "30s"
    # execution.checkpointing.timeout: "10min"
    # execution.checkpointing.mode: EXACTLY_ONCE
    state.checkpoints.dir: "s3://eks-flink-prod-bucket/parsed-checkpoints"
    state.savepoints.dir: "s3://eks-flink-prod-bucket/savepoints"
    pipeline.jars: local:///opt/flink/lib/flink-connector-kafka-3.4.0-1.20.jar
    # pipeline.classpaths: "local:///opt/flink/lib/flink-connector-kafka-1.17.2.jar"
  podTemplate:
    # spec:
    #   nodeSelector:
    #     eks.amazonaws.com/nodegroup: flink-ng
    
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - telemetry-ng

    # spec:
    #   nodeSelector:
    #     eks.amazonaws.com/nodegroup: flink-ng
      # tolerations:
      #   - key: "flink-node"
      #     operator: "Exists"
      #     # value: "true"
      #     effect: "NoSchedule"

  jobManager:
    resource:
      memory: "6144m"
      cpu: 1
  taskManager:
    resource:
      memory: "3584m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/lib/flink-connector-kafka-3.4.0-1.20.jar  # Dummy JAR, required for FlinkDeployment
    args: ["-py", "/opt/pyflink-job/main.py", "--pyFiles", "dependencies.zip"]
    # args:
    #   - "--pyExecutable"
    #   - "/usr/bin/python3"  
    #   - "--pyfs"
    #   - "local:///opt/pyflink-job/dependencies.zip"  
    #   - "--py"
    #   - "/opt/pyflink-job/main.py"
    parallelism: 20
    state: running

 